
- name: create directory for {{ pipeline }}  resources
  file:
    path: "{{ ngi_containers }}/{{ pipeline }}"
    state: directory

# the eutils service will only tolerate 3 requests / second so make sure not to exceed this
- name: download FASTA references
  get_url:
    url: "{{ ncbi_eutils_url }}/efetch.fcgi?db=nuccore&rettype=fasta&retmode=text&id={{ item.accession }}"
    dest: "{{ ngi_containers }}/{{ pipeline }}/{{ item.name }}_{{ item.accession }}.fa"
    checksum: "sha1:{{ item.sha1 }}"
  with_items: extra_parameters.references

# add methylseq-specific options to pipeline nextflow config
- name: "add specific parameters to {{ site }} {{ pipeline }} nextflow config - 1"
  lineinfile:
    dest: "{{ ngi_pipeline_conf }}/{{ pipeline }}_{{ site }}.config"
    line: "params { genomes { "
    backup: no

- name: "add specific parameters to {{ site }} {{ pipeline }} nextflow config - 2"
  lineinfile:
    dest: "{{ ngi_pipeline_conf }}/{{ pipeline }}_{{ site }}.config"
    line: "'{{ item.name }}' { fasta = \"{{ ngi_containers }}/{{ pipeline }}/{{ item.name }}_{{ item.accession }}.fa\" }"
    backup: no
  with_items: extra_parameters.references

- name: "add specific parameters to {{ site }} {{ pipeline }} nextflow config - 3"
  lineinfile:
    dest: "{{ ngi_pipeline_conf }}/{{ pipeline }}_{{ site }}.config"
    line: " } }"
  backup: no
