nf_core_env_name: nf-core-env
nf_core_env: "{{ sw_path }}/anaconda/envs/{{ nf_core_env_name }}"
nf_core_version: 2.4.1
nf_core_container_repo: docker://nfcore
nf_core_vars:
  NFCORE_NO_VERSION_CHECK: 1
  SINGULARITY_CACHEDIR: /scratch/{{ deployment_version }}/singularity_cache
  SINGULARITY_TMPDIR: /scratch/{{ deployment_version }}/singularity_temp
  NXF_SINGULARITY_CACHEDIR: "{{ container_dir }}"
  NXF_SINGULARITY_LIBRARYDIR: "{{ container_dir }}"
  NXF_HOME: "{{ nextflow_local_env.NXF_HOME }}"
  JAVA_HOME: "{{ nextflow_local_env.NXF_JAVA_HOME }}"
  PATH: "{{ nf_core_env }}/bin:{{ tools_path.PATH }}"
biocontainers_dirname: biocontainers
pipelines:
  - name: rnaseq
    release: 3.8.1
    container_dir: "{{ biocontainers_dirname }}"
  - name: sarek
    release: "{{ sarek_tag }}"
    pipeline_specific_containers:
      - sarekvep
      - sareksnpeff
    pipeline_genomes:
      - GRCh38
      - GRCh37
      - GRCm38
      - CanFam3.1
  - name: methylseq
    release: 1.6.1
  - name: ampliseq
    release: 2.0.0
    silva_base_url: https://www.arb-silva.de/fileadmin/silva_databases/qiime
    silva_zip: Silva_132_release.zip
    container_dir: "{{ biocontainers_dirname }}"
  - name: atacseq
    release: 1.2.1
  - name: viralrecon
    release: 2.2
    container_dir: "{{ biocontainers_dirname }}"
  - name: rnafusion
    release: 2.1.0
  - name: nanoseq
    release: 3.0.0
    container_dir: "{{ biocontainers_dirname }}"
  - name: scrnaseq
    release: 2.0.0

nf_core_delivery_readmes:
  sarek:
    - DELIVERY.README.SAREK.txt
    - DELIVERY.README.SAREK.BATCH.txt
    - DELIVERY.README.SAREK.WES.md
    - apply_recalibration.sh
  rnaseq:
    - DELIVERY.README.RNASEQ.md
  methylseq:
    - DELIVERY.README.METHYLSEQ.md
