---

- name: ensure {{ arteria_service_name }} conf dir exists
  file:
    state: directory
    path: "{{ arteria_service_config_root }}"

- name: deploy {{ arteria_service_name }} app config
  template:
    src: archive_verify_app.config.j2
    dest: "{{ arteria_service_config_root }}/app.config"

- name: deploy {{ arteria_service_name }} logger config
  template:
    src: archive_verify_logger.config.j2
    dest: "{{ arteria_service_config_root }}/logger.config"

- name: modify uppsala's supervisord conf to set environment
  ini_file:
    dest: "{{ supervisord_conf }}"
    section: supervisord
    option: environment
    value: LC_ALL='en_US.UTF-8',LANG='en_US.UTF-8'
    backup: no

- name: modify uppsala's supervisord conf to start {{ arteria_service_name }}
  ini_file: 
    dest: "{{ supervisord_conf }}"
    section: program:{{ arteria_service_name }}-{{ deployment_environment }}
    option: command
    value: "{{ arteria_service_env_root }}/bin/pipenv run {{ arteria_service_src_path }}/archive-verify-ws --configroot={{ arteria_service_config_root }}"
    backup: no

- name: modify uppsala's supervisord conf to start {{ arteria_service_name }}
  ini_file:
    dest: "{{ supervisord_conf }}"
    section: program:{{ arteria_service_name }}-{{ deployment_environment }}
    option: environment
    value: PIPENV_VENV_IN_PROJECT="1"
    backup: no

- name: modify uppsala's supervisord conf to start {{ arteria_service_name }}
  ini_file: 
    dest: "{{ supervisord_conf }}"
    section: program:{{ arteria_service_name }}-{{ deployment_environment }}
    option: autorestart
    value: true
    backup: no

- name: modify uppsala's supervisord conf to start redis-server
  ini_file:
    dest: "{{ supervisord_conf }}"
    section: program:redis-server
    option: command
    value: "{{ arteria_service_env_root }}/bin/redis-server"
    backup: no

- name: modify uppsala's supervisord conf to start redis-server
  ini_file:
    dest: "{{ supervisord_conf }}"
    section: program:redis-server
    option: autorestart
    value: true
    backup: no

- name: modify uppsala's supervisord conf to start redis-worker
  ini_file:
    dest: "{{ supervisord_conf }}"
    section: program:redis-worker
    option: command
    value: "{{ arteria_service_env_root }}/bin/pipenv run rq worker"
    backup: no

- name: modify uppsala's supervisord conf to start redis-worker
  ini_file:
    dest: "{{ supervisord_conf }}"
    section: program:redis-worker
    option: autorestart
    value: true
    backup: no

- name: modify uppsala's supervisord conf to start redis-worker
  ini_file:
    dest: "{{ supervisord_conf }}"
    section: program:redis-worker
    option: environment
    value: PIPENV_VENV_IN_PROJECT="1"
    backup: no
